[package]
name = "sudoku_solver_lib"
version = "0.1.3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = { version = "0.32.5", features = ["serde-serialize"] }
serde_json = "1.0.117"
